IrnBruMvc/IrnBruMvc/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^topics_trainer/', include('topics_trainer.urls', namespace="topics_trainer")),
    url(r'^factors_trainer/', include('factors_trainer.urls', namespace="factors_trainer")),
    url(r'^article_summary/', include('article_summary.urls', namespace="article_summary")),
    url(r'^', include('front_page.urls', namespace="front_page")),
    url(r'^classifier/', include('classifier.urls', namespace="classifier")),
    url(r'^profile_setup/', include('profile_setup.urls', namespace='profile_setup')),
    url(r'^miner/', include('miner.urls', namespace='miner')),
    url(r'^admin/', include(admin.site.urls)),
)

IrnBruMvc/classifier/urls.py
from django.conf.urls import patterns, url

from classifier import views

urlpatterns = patterns('classifier', 
    url(r'^$', views.index, name='index'),
    url(r'classify_article/$', views.classify_article, name='classify_article')
)

IrnBruMvc/miner/urls.py
from django.conf.urls import patterns, url

from miner import views

urlpatterns = patterns('miner', 
    url(r'^$', views.index, name='index'),
    url(r'mine/$', views.mine, name='mine')
)

IrnBruMvc/classifier/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse
from django.template import RequestContext, loader
from django.shortcuts import redirect
from nltk.tokenize import *

from topics_trainer.models import Article

from classifier.topics_classifier import *
from classifier.factors_classifier import *

import collections


def index(request):
    template = loader.get_template('factors_classification.html')
    context = RequestContext(request, {})
    return HttpResponse(template.render(context))

def get_article_classification(article):
    article_classifier = TopicsClassifier()
    body = sent_tokenize(article)
    article_obj = Article(title='', body=body)
    return article_classifier.classify(article_obj)

def get_factors_classification(article, topic):

    classifier = FactorsClassifier(topic)
    bodies = sent_tokenize(article)
    article_obj = Article(title='', body=bodies)
    factors_list = [classifier.classify_sentence(sent).max() for sent in bodies]
    return factors_list

def get_factors_list_percentage(factors_list):
    print factors_list
    print factors_list.count('Yes')
    print factors_list.count('No')
    yes_percentage = round((float(factors_list.count('Yes'))/len(factors_list))*100,2)
    no_percentage = round((float(factors_list.count('No'))/len(factors_list))*100,2)
    return [
            {
                'label': 'Yes',
                'value': yes_percentage
                },
            {
                'label': 'No',
                'value': no_percentage
                }
            ]

def get_classify_distribution(dist):
    data = []
    for label in dist.samples():
        percent = int(100*(round(dist.prob(label),2)))
        print label
        print dist.prob(label)
        data.append({'label':label, 
        'value': dist.prob(label), 
        'percent': percent
        })
    return sorted(data, key=lambda dist:dist['value'], reverse=True)

def classify_article(request):
    if request.POST:
        article = __get_article__(request)
        dist = get_article_classification(article)
        data = get_classify_distribution(dist)
        dist_factors = get_factors_classification(article, dist.max())
        bodies = sent_tokenize(article)
        zipped = zip(bodies, dist_factors)
        factor_data = get_factors_list_percentage(dist_factors)
        template = loader.get_template('classification_report.html')
        context = RequestContext(request, { 
            'article_data': data,
            'factor_data': factor_data,
            'sentence_analysis': zipped
            })
        return HttpResponse(template.render(context))
    else:
        return HttpResponse('No data')

def __get_article__(request):
    article_type_map = {
            'article-text': __get_article_text__,
            'article_url': __get_article_url__,
            'article_file': __get_article_file__
            }
    article_type = request.POST['article-type']
    return article_type_map[article_type](request.POST[article_type])

def __get_article_url__(article_url):
    #TODO: Implement
    return ''

def __get_article_file__(article_file):
    #TODO: Implement
    return ''

def __get_article_text__(article_text):
    return article_text

IrnBruMvc/classifier/templates/base_classification.html
{% extends "base.html" %}

{% block content-wrapper %}
{% block content %} {% endblock %}
{% endblock %}

IrnBruMvc/classifier/templates/classification_report.html
{% extends "base_classification.html" %}
{% load staticfiles %}

{% block title %}
Article Report
{% endblock %}

{% block content %}
<div class='row'>
    <div class='col-md-6'>
        <div class='row'>
            <div class='col-md-12'>
                <div class='panel panel-default'>
                    <div class='panel-heading'>Factors Classification</div>
                    <div class='panel-body'>
                        {% for dist in factor_data%}
                        <h{{forloop.counter}}>{{ dist.label }} <small> {{ dist.value}}% </small></h1>
                        {% endfor %}
                    </div>
                </div>

            </div>
            <div class='col-md-12'>
                <div class='panel panel-default'>
                    <div class='panel-heading'>Topics Classification</div>
                    <div class='panel-body'>
                        {% for dist in article_data %}
                        <h{{forloop.counter}}>{{ dist.label }} <small> {{ dist.percent }}% </small></h1>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class='col-md-6'>
        <div class='row'>
            <div class='col-md-12'>
                <div class='panel panel-default'>
                    <div class='panel-heading'>Sentece-by-sentence analysis</div>
                    <div class='panel-body'>
                        {% for sent in sentence_analysis %}
                        {% if sent.1 == 'Yes' %}
                        <div class='alert alert-success' data-toggle-'tooltip' data-placement='right' title data-original-title='{{sent.1}}'>{{sent.0}}</div>
                        {% else %}
                        <div class='alert alert-danger' data-toggle-'tooltip' data-placement='right' title data-original-title='{{sent.1}}'>{{sent.0}}</div>
                        {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block sources %}
{% endblock %}

IrnBruMvc/classifier/templates/factors_classification.html
{% extends "base_classification.html" %}
{% load staticfiles %}

{% block title %}
Classify your article
{% endblock %}

{% block sources %}
<link href="{% static "dist/css/factors_classification.css" %}" rel="stylesheet"/>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <ul class="nav nav-tabs">
            <li class="active">
                <a href="#copy" data-toggle="tab" aria-expanded="true">Copy Over</a>
            </li>
            <li>
                <a href="#file" data-toggle="tab" aria-expanded="true">Send Over</a>
            </li>
            <li>
                <a href="#url" data-toggle="tab" aria-expanded="true">URL</a>
            </li>
        </ul>
        <div class="tab-content">
            <div id="copy" class="tab-pane fade active in"> 
                <form action='{% url 'classifier:classify_article' %}' method='POST' role="form">
                    {% csrf_token %}
                    <h4>Show us your article</h4>
                    <div class="form-group">
                        <textarea name='article-text' class="form-control" placeholder="Paste your article here..."></textarea>
                    </div>
                    <button type='submit' name='article-type' value='article-text' class='btn btn-outline btn-primary btn-lg btn-block'>Classify</button>
                </form>
            </div>
            <div id="file" class="tab-pane fade">
                <form action='{% url 'classifier:classify_article' %}' method='POST' role="form">
                    {% csrf_token %}
                    <h4>Send us your article</h4>
                    <div class="form-group">
                        <input name='article-file' type="file"/>
                    </div>
                    <button type='submit' name='article-type' value='article-text' class='btn btn-outline btn-primary btn-lg btn-block'>Classify</button>
                </form>
            </div>

            <div id="url" class="tab-pane fade">
                <form action='{% url 'classifier:classify_article' %}' method='POST' role="form">
                    {% csrf_token %}
                    <h4>Link us up</h4>
                    <div class="form-group">
                        <input name='article-url' type='text' placeholder='Paste your article URL here' class='form-control' id='article-url'/>
                    </div>
                    <button type='submit' name='article-type' value='Classify' class='btn btn-outline btn-primary btn-lg btn-block'>Classify</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}