IrnBruMvc/IrnBruMvc/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^topics_trainer/', include('topics_trainer.urls', namespace="topics_trainer")),
    url(r'^factors_trainer/', include('factors_trainer.urls', namespace="factors_trainer")),
    url(r'^article_summary/', include('article_summary.urls', namespace="article_summary")),
    url(r'^', include('front_page.urls', namespace="front_page")),
    url(r'^classifier/', include('classifier.urls', namespace="classifier")),
    url(r'^profile_setup/', include('profile_setup.urls', namespace='profile_setup')),
    url(r'^miner/', include('miner.urls', namespace='miner')),
    url(r'^admin/', include(admin.site.urls)),
)

IrnBruMvc/miner/urls.py
from django.conf.urls import patterns, url

from miner import views

urlpatterns = patterns('miner', 
    url(r'^$', views.index, name='index'),
    url(r'mine/$', views.mine, name='mine')
)

IrnBruMvc/topics_trainer/urls.py
from django.conf.urls import patterns, url

from topics_trainer import views

urlpatterns = patterns('topics_trainer', 
    url(r'^(?P<article_id>.*)/update_topic/$', views.update_topic, name='update_topic'),
    url(r'^$', views.index, name='index'),
    url(r'^(?P<article_id>\w+)/$', views.article_choice, name='article_choice')
)

IrnBruMvc/topics_trainer/models.py
from django.db import models
from djangotoolbox.fields import ListField, EmbeddedModelField

class Article(models.Model):
    title = models.CharField(max_length=200)
    body = ListField(models.CharField(models.TextField()))
    source = models.CharField(max_length=200)

class Choice(models.Model):
    choice = models.ForeignKey(Article)
    topic = ListField(models.CharField(max_length=200))

IrnBruMvc/topics_trainer/forms.py
from django import forms
from django.core.exceptions import ValidationError

IrnBruMvc/topics_trainer/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse
from django.template import RequestContext, loader

from topics_trainer.models import Article, Choice
from topics_editor.models import Topic

def choice_exists(article):
    choice = Choice.objects.filter(choice=article)
    if choice.exists():
        return 'Done'
    else:
        return ''

def index(request):
    template = loader.get_template('articles_list.html')
    articles = [(article, choice_exists(article)) for article in Article.objects.all()]
    context = RequestContext(request, {
        'articles': articles
        })
    return HttpResponse(template.render(context))

def article_choice(request, article_id):
    article = Article.objects.get(id=article_id)
    topics = Topic.objects.all()

    template = loader.get_template('article_choice.html')

    try:
        choice = Choice.objects.get(choice=article)
        context = RequestContext(request, {
            'article': article,
            'topics': topics,
            'chosen_topics': choice.topic
        })
    except ObjectDoesNotExist:
        context = RequestContext(request, {
            'article': article,
            'topics': topics,
        })

    return HttpResponse(template.render(context))

def update_topic(request, article_id):
    if request.POST:
        topic_keys = request.POST.getlist('topics')
        currentarticle = Article.objects.get(id=article_id)
        try: 
            choice = Choice.objects.get(choice=currentarticle)
            choice.topic = topic_keys
            choice.save(force_update=True)
        except ObjectDoesNotExist:
            choice = Choice(choice=currentarticle, topic=topic_keys)
            choice.save()
        return HttpResponse("Update")
    else:
        return HttpResponse("Get")

IrnBruMvc/topics_trainer/templates/article_choice.html
{% extends "base_topics_trainer.html" %}
{% load staticfiles %}

{% block title %}
{% if article %}
<h1> {{ article.title.0 }} </h1>
{% else %}
Invalid Article
{% endif %}
{% endblock %}

{% block content %}
<div class="col-md-10"> 
    <div class='panel panel-default'>
        <div class='panel-heading'> Article </div>
        <div class='panel-body'>
            {% for sent in article.body%}
            <p> {{ sent }} </p>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

{% block topics %}
<div class="col-md-2"> 
    <div class='panel panel-default'>
        <div class='panel-heading'> Topic </div>
        <div class='panel-body'>
            <form action="{% url 'topics_trainer:update_topic' article.id %}" method="POST">
                {% csrf_token %}
                <div class="checkbox">
                    {% for topic in topics %}
                    <label class="topic_label">
                        <div class='checkbox'>
                            {% if topic.id in chosen_topics %}
                            <input type="checkbox" name="topics" id="topics"  value="{{ topic.id }}" checked/> 
                            {% else %}
                            <input type="checkbox" name="topics" id="topics"  value="{{ topic.id }}"/> 
                            {% endif %}
                            {{ topic.topic.title }} 
                        </div>
                    </label>
                    {% endfor %}
                </div>
                <input type="submit" value="Update"/>
            </form>
        </div>
    </div>
</div>
{% endblock %}

IrnBruMvc/topics_trainer/templates/articles_list.html
{% extends "base_topics_trainer.html" %}
{% load staticfiles %}

{% block title %}
Article List
{% endblock %}

{% block content %}
<div class='col-lg-12'>
    <table id='articles-table' class='table table-bordered table-striped table-hover display' cellspacing='0' width='100%'>
        <thead>
            <tr>
                <th> Article Title </th>
                <th> Source </th>
                <th> Labelled </th>
            </tr>
        </thead>
        <tbody>
            {% for article in articles %}
            <tr>
                <td> <a href='{{ article.0.id }}'>{{ article.0.title.0 }} </a></td>
                <td> {{ article.0.source }} </td>
                <td> {{article.1}}</td> 
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

{% block sources %}
<script>
    $(document).ready(function() {
        $('#articles-table').DataTable();
    });
</script>
{% endblock %}

IrnBruMvc/topics_trainer/templates/base_topics_trainer.html
{% extends "base.html" %}
{% block content-wrapper %}
{% block content %} {% endblock %} 
{% block topics %} {% endblock %} 
{% endblock%}