IrnBruMvc/IrnBruMvc/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^topics_trainer/', include('topics_trainer.urls', namespace="topics_trainer")),
    url(r'^factors_trainer/', include('factors_trainer.urls', namespace="factors_trainer")),
    url(r'^article_summary/', include('article_summary.urls', namespace="article_summary")),
    url(r'^', include('front_page.urls', namespace="front_page")),
    url(r'^classifier/', include('classifier.urls', namespace="classifier")),
    url(r'^profile_setup/', include('profile_setup.urls', namespace='profile_setup')),
    url(r'^miner/', include('miner.urls', namespace='miner')),
    url(r'^admin/', include(admin.site.urls)),
)

IrnBruMvc/factors_trainer/urls.py
from django.conf.urls import patterns, url

from factors_trainer import views

urlpatterns = patterns('factors_trainer', 
    url(r'update/$', views.update, name='index'),
    url(r'get_factor/(?P<topic_name>[\w|\W]+)/$', views.get_factors, name='get_factors'),
    url(r'update_factor/(?P<factor_id>.*)/$', views.update_factor, name='update_factor'),
    url(r'^$', views.index, name='index'),
    # Reporting
    url(r'report/(?P<topic_name>\w+)/(?P<sentiment>\w*)/$', views.report_topic_factor_sentiments, name='report_topic_factor_sentiments'),
    url(r'report/(?P<topic>\w+)/$', views.report_sentiments, name='report_sentiments'),
    url(r'report/$', views.report, name='report')
)

IrnBruMvc/miner/urls.py
from django.conf.urls import patterns, url

from miner import views

urlpatterns = patterns('miner', 
    url(r'^$', views.index, name='index'),
    url(r'mine/$', views.mine, name='mine')
)

IrnBruMvc/factors_trainer/models.py
from django.db import models
from djangotoolbox.fields import EmbeddedModelField

# Create your models here.
class Factor(models.Model):
    article = models.ForeignKey('topics_trainer.Article')
    topic = models.ForeignKey('topics_editor.Topic')
    factor = models.CharField(max_length=2000)
    sentiment = models.CharField(max_length=200)

IrnBruMvc/factors_trainer/forms.py
from django import forms

class FactorForm(forms.Form):
    factor_id = forms.CharField(max_length=100)
    sentiment = forms.CharField(max_length=7)

IrnBruMvc/factors_trainer/views.py
# Create your views here.

from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse
from django.template import RequestContext, loader

from factors_trainer.factors import *
from topics_editor.models import Topic

def index(request):
    template = loader.get_template('topics_factors_list.html')
    topics = Topic.objects.all()
    context = RequestContext(request, {
        'topics': topics
        })
    return HttpResponse(template.render(context))


def get_factors(request, topic_name):
    template = loader.get_template('factors_list.html')
    topic = Topic.objects.get(topic = topic_name)
    factors = [factor for factor in get_factors_for_topic(topic) if factor.sentiment == '']
    context = RequestContext(request, {
        'factors': factors,
        'topic_name': topic_name.title()
        })
    return HttpResponse(template.render(context))

def report_topic_factor_sentiments(request, topic_name, sentiment):
    topic = Topic.objects.get(topic=topic_name)
    template = loader.get_template('report.html')
    factors = get_factors_with_sentiment(sentiment)
    topic_factors = [factor for factor in factors if factor.topic == topic]
    context = RequestContext(request, {
        'factors': topic_factors,
        'sentiment': sentiment
        })
    return HttpResponse(template.render(context))

def report_sentiments(request, topic):
    template = loader.get_template('sentiments_list.html')
    sentiments = ['Yes', 'No', 'Neutral']
    context = RequestContext(request, {
        'topic': topic,
        'sentiments': sentiments
        })
    return HttpResponse(template.render(context))

def report(request):
    template = loader.get_template('report_topics_list.html')
    topics = Topic.objects.all()
    context = RequestContext(request, {
        'topics': topics
        })
    return HttpResponse(template.render(context))

def update(request):
    update_factors()
    return HttpResponse('Updated')

def update_factor(request, factor_id):
    factor = Factor.objects.get(id=factor_id)
    if request.POST:
        try:
            sentiment = request.POST['sentiment']
        except KeyError:
            sentiment = ''
        factor.sentiment = sentiment
        factor.save()
        return HttpResponse(sentiment)
    else:
        return HttpResponse('Not updated')

IrnBruMvc/factors_trainer/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
    <head>
        <title> IrnBru - The Scottish Referendum Miner </title>
        <!-- Latest compiled and minified CSS -->

        <link rel="stylesheet" href="{% static "bower_components/bootstrap/dist/css/bootstrap.min.css" %}"/>

        <link href="{% static "bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css" %}" rel="stylesheet"/>
        <link href="{% static "bower_components/datatables-responsive/css/dataTables.responsive.css" %}" rel="stylesheet"/>
        <link rel="stylesheet" href="{% static "dist/css/timeline.css" %}"/>

        <!--link rel="stylesheet" href="{% static "stylesheets/topics_trainer.css" %}"/-->
        <link href="{% static "dist/css/sb-admin-2.css" %}" rel="stylesheet"/>

        <!-- Morris Charts CSS -->
        <link href="{% static "bower_components/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet" type="text/css"/>
        <link href="{% static "bower_components/metisMenu/dist/metisMenu.min.css" %}" rel="stylesheet"/>



        <!-- Latest compiled and minified JavaScript -->
        <script src="{% static "bower_components/jquery/dist/jquery.min.js" %}"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="{% static "bower_components/bootstrap/dist/js/bootstrap.min.js" %}"></script>

        <!-- Metis Menu Plugin JavaScript -->
        <script src="{% static "bower_components/metisMenu/dist/metisMenu.min.js" %}"></script>

        <!-- Morris Charts JavaScript -->
        <script src="{% static "bower_components/raphael/raphael-min.js" %}"></script>
        <script src="{% static "bower_components/morrisjs/morris.min.js" %}"></script>
        <!--<script src="{% static "js/morris-data.js" %}"></script>-->

        <!-- Custom Theme JavaScript -->
        <script src="{% static "dist/js/sb-admin-2.js" %}"></script>
        <script src="{% static "bower_components/datatables/media/js/jquery.dataTables.min.js" %}"></script>
        <script src="{% static "bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js" %}"></script>

        {% block sources %}{% endblock %}


        <!--<script src="{% static "javascripts/topics_trainer.js" %}"></script>-->
        <!-- Latest compiled and minified CSS -->
    </head>

    <body>
        <div id='wrapper'>
            <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="index.html"><i class='fa fa-bank fa-fw'></i> IrnBru</a>
                </div>
                <!-- /.navbar-header -->

                <ul class="nav navbar-top-links navbar-right">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                            </li>
                            <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                            </li>
                            <li class="divider"></li>
                            <li><a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                            </li>
                        </ul>
                        <!-- /.dropdown-user -->
                    </li>
                    <!-- /.dropdown -->
                </ul>
                <!-- /.navbar-top-links -->

                <div class="navbar-default sidebar" role="navigation">
                    <div class="sidebar-nav navbar-collapse">
                        <ul class="nav" id="side-menu">
                            <li class="sidebar-search">
                                <div class="input-group custom-search-form">
                                    <input type="text" class="form-control" placeholder="Coming Soon" disabled/>
                                    <span class="input-group-btn">
                                        <button class="btn btn-default" type="button" disabled>
                                            <i class="fa fa-search"></i>
                                        </button>
                                    </span>
                                </div>
                            </li>
                            <li>
                                <a href="/dashboard"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                            </li>
                            <li>
                                <a href='/classifier'><i class="fa fa-edit fa-fw"></i> Classifier </a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-bolt fa-fw"></i> Trainer<span class="fa arrow"></span></a>
                                <ul class="nav nav-second-level">
                                    <li>
                                        <a href="/topics_trainer/">Topics </a>
                                    </li>
                                    <li>
                                        <a href="/factors_trainer/"> Factors </a>
                                    </li>
                                </ul>

                            </li>
                            <li>
                                <a href="/factors_trainer/report/"><i class="fa fa-line-chart fa-fw"></i> Classifier Report </a>
                            </li>

                            <li>
                                <a href='/profile_setup'><i class="fa fa-file-text-o fa-fw"></i> Profile Setup</a>
                            </li>
                            <li>
                                <a href='/miner'><i class="fa fa-cubes fa-fw"></i> Miner </a>
                            </li>
                        </ul>
                    </div>
                    <!-- /.sidebar-collapse -->
                </div>
                <!-- /.navbar-static-side -->
            </nav>

            <div class='container' id='page-wrapper'>
                <div class="row">
                    <div class="page-header">
                        <h1>{% block title %} Title {% endblock %}</h1>
                    </div>
                </div>

                <div class="row">
                        {% block content-wrapper %} {% endblock%}
                </div>
            </div>

        </div>
    </body>
</html>

IrnBruMvc/factors_trainer/templates/base_factors_trainer.html
{% extends "base.html" %}
{% block content-wrapper %}
 {% block content %} {% endblock %} 
{% endblock %}

IrnBruMvc/factors_trainer/templates/factors_list.html
{% extends "base_factors_trainer.html" %}
{% load staticfiles %}

{% block title %}
{{ topic_name }} Factors Listing
{% endblock %}

{% block content %}
<div class='row'>
    <div class='col-lg-12'>
        <table id='factors-table' class='table table-bordered table-striped table-hover display' cellspacing='0' width='100%'>
            <thead>
                <tr>
                    <th> Factor </th>
                    <th> Sentiment option </th>
                </tr>
            </thead>
            <tbody>
                {% for factor in factors %}
                <tr>
                    <td> {{ factor.factor }} </td>
                    <td> 
                        <form class='text-center' style='width:180px' action="{% url 'factors_trainer:update_factor' factor.id %}" method="POST">
                            {% csrf_token %}
                            <div class="btn-group" data-toggle="buttons">
                                <label class="btn btn-outline btn-primary">
                                    <input type="checkbox" name="sentiment" value='Yes' autocomplete="off"/> Yes
                                </label>
                                <label class="btn btn-outline btn-primary">
                                    <input type="checkbox" name="sentiment" value='No' autocomplete="off"/> No
                                </label>
                                <label class="btn btn-outline btn-primary">
                                    <input type="checkbox" name="sentiment" value='Neutral' autocomplete="off"/> Neutral
                                </label>
                            </div>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

{% block sources %}
<script src="{% static "javascripts/factors_trainer.js" %}"></script>
{% endblock %}

IrnBruMvc/factors_trainer/templates/factors_trainer.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
<h1>Factors Training</h1>
{% endblock %}

{% block content %}
<div class='text-center'>
    <h1> {{ sentence }} </h1>
</div>
<div class='btn-group btn-group-justified' role='group'>
    <div class="btn-group" role="group">
        <button type="button" class="btn btn-default">Independence </button>
    </div>
    <div class="btn-group" role="group">
        <button type="button" class="btn btn-default">Better Together</button>
    </div>
    <div class="btn-group" role="group">
        <button type="button" class="btn btn-default">No Comments</button>
    </div>
</div>
{% endblock %}

IrnBruMvc/factors_trainer/templates/report.html
{% extends "base_factors_trainer.html" %}

{% block title %}
Report: {{ sentiment.title }}
{% endblock %}

{% block content %}
{% for factor in factors %}
<div class='row'>
    <div class='col-md-12'>
        {{ factor.factor }}
        <hr/> 
    </div>
</div>
{% endfor %}
{% endblock %}

IrnBruMvc/factors_trainer/templates/report_topics_list.html
{% extends "base_factors_trainer.html" %}

{% block title %}
Factors Report - Topics Selection
{% endblock %}

{% block content %}
<div class='col-lg-12'>
    <table id='topics-table' class='table table-bordered table-striped table-hover display' cellspacing='0' width='100%'>
        <thead>
            <tr>
                <th> Topic </th>
            </tr>
        </thead>
        <tbody>
            {% for topic in topics %}
            <tr>
                <td> <a href='{{ topic.topic }}'>{{ topic.topic }} </a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

{% block sources %}
<script>
    $(document).ready(function() {
        $('#topics-table').DataTable();
    });
</script>
{% endblock %}

IrnBruMvc/factors_trainer/templates/sentiments_list.html
{% extends "base_factors_trainer.html" %}

{% block title %}
{{ topic.title }}: Sentiment Selection
{% endblock %}

{% block content %}
<div class='col-lg-12'>
    <table id='sentiments-table' class='table table-bordered table-striped table-hover display' cellspacing='0' width='100%'>
        <thead>
            <tr>
                <th> Sentiment </th>
            </tr>
        </thead>
        <tbody>
            {% for sentiment in sentiments %}
            <tr>
                <td> <a href='{{ sentiment }}'>{{sentiment }} </a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

{% block sources %}
<script>
    $(document).ready(function() {
        $('#sentiments-table').DataTable();
    });
</script>
{% endblock %}

IrnBruMvc/factors_trainer/templates/topics_factors_list.html
{% extends "base_factors_trainer.html" %}

{% block title %}
Topics Factors Listing
{% endblock %}

{% block content %}
<div class='row'>
    <div class='col-lg-2'>
        <form>
            {% csrf_token %}
            <button class='btn btn-outline btn-primary' id='update'>Update</button>
        </form>
    </div>
</div>

<div class='row'>
    <div class='col-lg-12'>
        <br/>
        <table id='topics-table' class='table table-bordered table-striped table-hover display' cellspacing='0' width='100%'>
            <thead>
                <tr>
                    <th> Topic </th>
                </tr>
            </thead>
            <tbody>
                {% for topic in topics %}
                <tr>
                    <td> <a href='get_factor/{{ topic.topic }}'>{{ topic.topic }} </a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

{% block sources %}
<script>
    $(document).ready(function() {
        $('#topics-table').DataTable();
        $('#update').on('click', function(e) {
            console.log('clicking');
            e.preventDefault();
            $.ajax({
                    type: 'GET',
                    url: 'update/',
                    beforeSend: function() {
                        $('#update').text('Updating...');
                    },
                    success: function(data) {
                        $('#update').text('Update');
                    }
            });
            return false;
        });
    });
</script>
{% endblock %}